version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: ~/-integration_test/src
    docker:
      - image: cimg/node:lts
    steps:
      -checkout:
        path: ~/-integration_test/
      -run: npm install 